additional_commands:
  nrn_add_test_group:
    pargs: 0
    kwargs:
      NAME: 1
      SUBMODULE: '?'
      MODFILE_PATTERNS: '*'
      SCRIPT_PATTERNS: '*'
      OUTPUT: '*'
  nrn_add_test:
    pargs: 0
    kwargs:
      GROUP: 1
      NAME: 1
      SUBMODULE: '?'
      MODFILE_PATTERNS: '*'
      COMMAND: '+'
      SCRIPT_PATTERNS: '*'
      REQUIRES: '*'
      CONFLICTS: '*'
  nrn_add_test_group_comparison:
    pargs: 0
    kwargs:
      GROUP: 1
      REFERENCE_OUTPUT: '*'
