version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - build-essential
    - libx11-dev
    - libxcomposite-dev
    - libmpich-dev
    - ffmpeg
    - doxygen
    - pandoc

submodules:
  recursive: true

python:
  install:
    - requirements: nrn_requirements.txt
    - requirements: docs/docs_requirements.txt
