version: 2

sphinx:
  configuration: docs/conf.py

search:
  ignore:
    - '*/doxygen/*'

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - build-essential
    - libx11-dev
    - libxcomposite-dev
    - libmpich-dev
    - ffmpeg
    - doxygen
    - pandoc
    - cmake
    - bison
    - flex
    - libfl-dev
    - libreadline-dev

submodules:
  recursive: true

python:
  install:
    - requirements: ci/requirements.txt
