#!/bin/sh
# installed mpich2 from mpich2-1.0.3-1-win32-ia32.msi from
# http://www-unix.mcs.anl.gov/mpi/mpich2/index.htm#download
# Note: "This setup requires the .NET Framwork version 1.1.4322..." 
# and they really mean 1.1, not 2.0 and not 1.0.
# Installed in c:/mpich2 to avoid spaces in paths.
# First get to the point where you can run cpi.exe example. May need to
# give yourself a login password.

export CFLAGS="-mwindows -I/cygdrive/c/mpich2/include"
export CXXFLAGS="-mwindows -I/cygdrive/c/mpich2/include"
export LIBS="-L/cygdrive/c/mpich2/lib -lmpi"
export LDFLAGS="-e _mainCRTStartup"

#build InterViews with above environment also

./configure --prefix=`pwd` --with-paranrn --with-iv=$HOME/neuron/ivmpi

# make
# make mswin
# in the src/parallel directory one can launch any of the tests with, e.g.
# c:/mpich2/bin/mpiexec -np 1 c:\\marshalnrn\\nrn\\bin\\nrniv.exe -mpi test0.hoc


if false
#notes about building with mpich2 under cygwin.
#I have used it with multicore desktops.
#In my $HOME
curl -O http://www.mcs.anl.gov/research/projects/mpich2/downloads/tarballs/1.0.7/mpich2-1.0.7.tar.gz
tar xzf mpich*gz
cd mpich*7
./configure --prefix=$HOME/mpich2 --with-device=ch3:nemesis \
  'pac_cv_f77_sizeof_integer=4' 'pac_cv_f77_sizeof_double_precision=8' \
  'CFLAGS=-DDLL_EXPORT -DPIC' 'CXXFLAGS=-DDLL_EXPORT -DPIC' \
  LDFLAGS='-Wl,--enable-auto-import'
make >& build.stdout
#did not do a "make install"
# note that the build.stdout is needed by src/mswin/nrncygso.sh
#For mpich2-1.1.1p1 I configured with:
./configure --prefix=$HOME/mpich2 --with-device=ch3:nemesis \
  'CFLAGS=-DDLL_EXPORT -DPIC' 'CXXFLAGS=-DDLL_EXPORT -DPIC' \
  'LDFLAGS=-Wl,--enable-auto-import' --enable-timer-type=gettimeofday

fi
