#pragma once
// See https://www.gnu.org/software/bison/manual/bison.html#g_t_0025header:
// ...if you are using a %union with components that require other
// definitions...you need to arrange for these definitions to be propagated to
// all modules, e.g., by putting them in a prerequisite header that is included
// both by your parser and by any other module that needs YYSTYPE.
#include "hocdec.h"
#include "parse.hpp"  // generated by bison
