# Generated by myneuron scripts/export_to_nrn.py; do not edit.
set(NRN_PYTHON_INTERFACE_FILES_LIST
    _interface/__init__.py
    _interface/_docs.py
    _interface/_facades.py
    _interface/_provenance.py
    _interface/_startup.py
    _interface/api.py
    _interface/gui.py
    _interface/mechanism.py
    _interface/nrnref.py
    _interface/object.py
    _interface/plotting.py
    _interface/sections.py
    _interface/utils.py)
