#define NRN_MAJOR_VERSION "6"
#define NRN_MINOR_VERSION "2"
#define SVN_DATE "2008-08-22"
#define SVN_BRANCH "unoffical-nrn-hg"
#define SVN_CHANGESET "(2194)"
#define SVN_TREE_CHANGE "unknown"
#define SVN_BASE_CHANGESET "2194"
