#define NRN_MAJOR_VERSION "7"
#define NRN_MINOR_VERSION "0"
#define SVN_DATE "2008-09-15"
#define SVN_BRANCH "unoffical-nrn-hg"
#define SVN_CHANGESET "(2216)"
#define SVN_TREE_CHANGE "unknown"
#define SVN_BASE_CHANGESET "2216"
