import sys
import re

outdir = sys.argv[-1]
input = "nrnmpidec.h"


def read(input):
    data = []
    with open(input, "r") as f:
        lines = [line.strip() for line in f]

    for line in lines:
        stripped = line.strip()
        # split on whitespace, but capture '(', ')', and ',' as separate tokens
        # The regex splits on \s+ (whitespace) and includes [(),] as captured groups
        tokens = [
            token
            for token in re.split(r"(\s+|[(),])", stripped)
            if token and not token.isspace()
        ]  # Filter out empty or pure whitespace

        if len(tokens) > 3 and tokens[0] == "extern":
            if tokens[2].startswith("nrnmpi_"):
                data.append(tokens[1:])
            elif tokens[3].startswith("nrnmpi_"):
                data.append(tokens[2:])

    return data


data = read(input)
# each item is [type, nrnmpi_name, argtokens]


def proto(tokens):
    s = " ".join(tokens[2:-1])
    return s


def args(tokens):
    istart = 2
    assert tokens[istart] == "("
    iend = len(tokens) - 2  # skip ';'
    assert tokens[iend] == ")"
    s = tokens[iend]
    i = iend - 1
    while i > istart:
        add = False
        if tokens[i] == ",":
            add = True
        elif tokens[i + 1] == "," or tokens[i + 1] == ")":
            add = True
        if add:
            s = tokens[i] + s
        i -= 1
    assert tokens[i] == "("
    s = tokens[i] + s
    return s


# generate nrnmpi_dynam_wrappers.inc
def gen1(output):
    with open(output, "w") as f:
        for x in data:
            s = "%s (%s)%s {" % (x[0], x[1], proto(x))
            print(s, file=f)
            ret = "    " if x[0] == "void" else "    return "
            s = "%s(*p_%s)%s;" % (ret, x[1], args(x))
            print(s + "\n}", file=f)


# generate nrnmpi_dynam.h
def gen2(output):
    with open(output, "w") as f:

        print(
            """
#ifndef nrnmpi_dynam_h
#define nrnmpi_dynam_h
/* generated by mkdynam.sh */

#if NRNMPI_DYNAMICLOAD\n""",
            file=f,
        )
        for x in data:
            s = "#define %s f_%s" % (x[1], x[1])
            print(s, file=f)

        print(
            """
#endif /* NRNMPI_DYNAMICLOAD */
 
#endif\n""",
            file=f,
        )


# generate nrnmpi_dynam_cinc
def gen3(output):
    with open(output, "w") as f:
        for x in data:
            s = "static %s (*p_%s)%s;" % (x[0], x[1], proto(x))
            print(s, file=f)

        print(
            """
static struct {
        const char* name;
        void** ppf;
} ftable[] = {""",
            file=f,
        )

        for x in data:
            s = '    {"f_%s", (void**)&p_%s},' % (x[1], x[1])
            print(s, file=f)

        print("    {0, 0}\n};", file=f)


gen1(outdir + "/nrnmpi_dynam_wrappers.inc")
gen2(outdir + "/nrnmpi_dynam.h")
gen3(outdir + "/nrnmpi_dynam_cinc")
