#!/bin/sh

names=`sed -n '
/extern /s/extern [a-z*]* \(nrnmpi_[a-zA-Z0-9_]*\)(.*/\1/p
/BGPDMA/s/.*/BGPDMA/p
$s/.*/ENDIF/p
' nrnmpidec.h`

#generate nrnmpi_dynam.h
(
echo '
#ifndef nrnmpi_dynam_h
#define nrnmpi_dynam_h
/* generated by mkdynam.sh */
#if defined(__cplusplus)
extern "C" {
#endif

#if NRNMPI_DYNAMICLOAD
'
for i in $names ; do
	if test "$i" = "BGPDMA" ; then
		echo "#if BGPDMA"
	elif test "$i" = "ENDIF" ; then
		echo "#endif"
	else
		echo "#define $i (*p_$i)"
	fi
done

echo '
#endif /* NRNMPI_DYNAMICLOAD */

#if defined(__cplusplus)
}
#endif

#endif
'
) > nrnmpi_dynam.h

(
echo '
typedef void(*PFRV)();
PFRV
'
for i in $names ; do
	if test "$i" = "BGPDMA" ; then
		echo "#if BGPDMA"
	elif test "$i" = "ENDIF" ; then
		echo "#endif"
	else
		echo "	p_$i,"
	fi
done
echo '	p_not_used;'
echo '
static struct {
	char* name;
	PFRV* ppf;
}ftable[] = {'
for i in $names ; do
	if test "$i" = "BGPDMA" ; then
		echo "#if BGPDMA"
	elif test "$i" = "ENDIF" ; then
		echo "#endif"
	else
		echo "	\"$i\", &p_$i,"
	fi
done
echo '	0,0
};
'
) > nrnmpi_dynam_cinc

