#!/usr/bin/env python3
"""Generate dynamic-MPI glue from nrnmpidec.h (replaces mkdynam.sh).

Reads nrnmpidec.h in the current directory. Writes to the output directory
given as the last argument:

  nrnmpi_dynam_wrappers.inc
  nrnmpi_dynam.h
  nrnmpi_dynam_cinc
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DECL = re.compile(r"^extern\s+(?:NRN_DLLSYM\s+)?(\S+)\s+(nrnmpi_\w+)\((.*)\);\s*$")


def declarations(path: Path) -> list[tuple[str, str, str]]:
    found: list[tuple[str, str, str]] = []
    for line in path.read_text().splitlines():
        match = DECL.match(line.strip())
        if match:
            found.append((match.group(1), match.group(2), match.group(3)))
    return found


def call_args(proto: str) -> str:
    proto = proto.strip()
    if not proto:
        return ""
    names: list[str] = []
    for arg in proto.split(","):
        ids = re.findall(r"[A-Za-z_]\w*", arg)
        if ids:
            names.append(ids[-1])
    return ", ".join(names)


def write_wrappers(path: Path, decls: list[tuple[str, str, str]]) -> None:
    lines: list[str] = []
    for ret, name, proto in decls:
        prefix = "  " if ret == "void" else "  return "
        lines.append(f"{ret} {name}({proto}) {{")
        lines.append(f"{prefix}(*p_{name})({call_args(proto)});")
        lines.append("}")
    path.write_text("\n".join(lines) + "\n")


def write_dynam_h(path: Path, decls: list[tuple[str, str, str]]) -> None:
    body = "\n".join(f"#define {name} f_{name}" for _, name, _ in decls)
    path.write_text(
        "\n"
        "#ifndef nrnmpi_dynam_h\n"
        "#define nrnmpi_dynam_h\n"
        "/* generated by mkdynam.py */\n"
        "\n"
        "#if NRNMPI_DYNAMICLOAD\n"
        "\n"
        f"{body}\n"
        "\n"
        "#endif /* NRNMPI_DYNAMICLOAD */\n"
        "\n"
        "#endif\n"
        "\n"
    )


def write_cinc(path: Path, decls: list[tuple[str, str, str]]) -> None:
    ptrs = [f"static {ret} (*p_{name})({proto});" for ret, name, proto in decls]
    table = [f'\t"f_{name}", (void**)&p_{name},' for _, name, _ in decls]
    path.write_text(
        "\n".join(ptrs)
        + "\n"
        + """
static struct {
	const char* name;
	void** ppf;
} ftable[] = {
"""
        + "\n".join(table)
        + "\n"
        + "	0,0\n"
        + "};\n"
        + "\n"
    )


def main(argv: list[str]) -> None:
    if len(argv) < 2:
        sys.exit("usage: mkdynam.py <output-directory>")
    outdir = Path(argv[-1])
    outdir.mkdir(parents=True, exist_ok=True)
    decls = declarations(Path("nrnmpidec.h"))
    if not decls:
        sys.exit("mkdynam.py: no extern nrnmpi_* prototypes in nrnmpidec.h")
    write_wrappers(outdir / "nrnmpi_dynam_wrappers.inc", decls)
    write_dynam_h(outdir / "nrnmpi_dynam.h", decls)
    write_cinc(outdir / "nrnmpi_dynam_cinc", decls)


if __name__ == "__main__":
    main(sys.argv)
