import pytest
from .testutils import compare_data, tol
from platform import platform


def applearm():
    return "macOS-" in platform() and "-arm64-" in platform()


@pytest.fixture
def model_pump(neuron_instance):
    """A simple rxd implementation of the sodium-potassium pump"""

    h, rxd, data, save_path = neuron_instance
    dend = h.Section(name="dend")
    dend.diam = 2
    dend.nseg = 101
    dend.L = 100

    cyt = rxd.Region(dend, name="cyt", nrn_region="i")
    ecs = rxd.Region(dend, name="ecs", nrn_region="o")
    mem = rxd.Region(dend, name="mem", geometry=rxd.membrane())
    na = rxd.Species(
        [cyt, ecs],
        name="na",
        charge=1,
        initial=lambda nd: 18 if nd.region == cyt else 144,
    )
    k = rxd.Species(
        [cyt, ecs],
        name="k",
        charge=1,
        initial=lambda nd: 140 if nd.region == cyt else 3,
    )

    nai, nao, ki, ko = na[cyt], na[ecs], k[cyt], k[ecs]
    exp = rxd.rxdmath.exp
    pump = (0.8 / (1.0 + exp((25.0 - nai) / 3.0))) * (1.0 / (1.0 + exp(3.5 - ko)))
    volume_scale = 1e-18 * rxd.constants.NA() * (dend.diam / 4.0)
    pump_current = rxd.MultiCompartmentReaction(
        2 * ko + 3 * nai,
        2 * ki + 3 * nao,
        pump * volume_scale,
        mass_action=False,
        membrane=mem,
        membrane_flux=True,
    )
    model = (
        dend,
        cyt,
        ecs,
        mem,
        na,
        k,
        nai,
        nao,
        ki,
        ko,
        pump,
        volume_scale,
        pump_current,
    )
    yield (neuron_instance, model)


def test_currents(model_pump):
    """Test currents generated by a Na/K-pump fixed step integration."""

    neuron_instance, model = model_pump
    h, rxd, data, save_path = neuron_instance
    h.finitialize(-65)
    h.continuerun(10)
    if not save_path:
        max_err = compare_data(data)
        assert max_err < tol


def test_currents_cvode(model_pump):
    """Test currents generated by a Na/K-pump variable step integration."""

    neuron_instance, model = model_pump
    h, rxd, data, save_path = neuron_instance
    h.CVode().active(True)
    h.finitialize(-65)
    h.continuerun(10)
    if not save_path:
        max_err = compare_data(data)
        assert max_err < (1e-8 if applearm() else tol)


def test_currents_stucture_change(model_pump):
    """Test currents generated by a Na/K-pump with change to structure"""

    neuron_instance, model = model_pump
    h, rxd, data, save_path = neuron_instance
    # check changing structure_change_cnt after initialization
    h.finitialize(-65)
    h.MechanismStandard("pas", 0)
    h.continuerun(10)
    if not save_path:
        max_err = compare_data(data)
        assert max_err < tol


def test_currents_model_change(model_pump):
    """Test currents generated by a Na/K-pump with post-initialization changes to the model"""
    neuron_instance, model = model_pump
    h, rxd, data, save_path = neuron_instance
    # check changing the model after initialization
    h.finitialize(-65)
    model[0].nseg = 11
    h.continuerun(10)
    if not save_path:
        max_err = compare_data(data)
        assert max_err < tol
