include_guard(GLOBAL)

# Git identity for nrnversion / neuron.__version__.
#
# cmake -P cmake/NrnGitInfo.cmake Host: write cmake/nrn-git-info.cmake (gitignored). Guest cmake
# cannot run git: this tree is a Linux worktree whose .git file points at
# /home/hines/neuron/nrn/.git/worktrees/msvc-port, which is not on the vboxsf share.
#
# add_cpp_git_information() uses live git when it works, else the stamp.

function(nrn_collect_git_info src_dir ok_var)
  set(${ok_var}
      FALSE
      PARENT_SCOPE)
  find_program(_nrn_git git)
  if(NOT _nrn_git)
    return()
  endif()
  execute_process(
    COMMAND "${_nrn_git}" -C "${src_dir}" describe
    OUTPUT_VARIABLE GIT_DESCRIBE
    RESULT_VARIABLE _nrn_git_r
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(_nrn_git_r OR "${GIT_DESCRIBE}" STREQUAL "")
    return()
  endif()
  execute_process(
    COMMAND "${_nrn_git}" -C "${src_dir}" rev-parse --abbrev-ref HEAD
    OUTPUT_VARIABLE GIT_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  execute_process(
    COMMAND "${_nrn_git}" -C "${src_dir}" -c log.showSignature=false log --format=%h -n 1
    OUTPUT_VARIABLE GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  execute_process(
    COMMAND "${_nrn_git}" -C "${src_dir}" -c log.showSignature=false log --format=%cd -n 1
            --date=short
    OUTPUT_VARIABLE GIT_DATE
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  execute_process(
    COMMAND "${_nrn_git}" -C "${src_dir}" status -s -uno --porcelain --ignore-submodules
    OUTPUT_VARIABLE GIT_STATUS
    ERROR_QUIET)
  if(GIT_STATUS)
    set(GIT_MODIFIED "+")
  else()
    set(GIT_MODIFIED "")
  endif()
  set(GIT_DATE
      "${GIT_DATE}"
      PARENT_SCOPE)
  set(GIT_BRANCH
      "${GIT_BRANCH}"
      PARENT_SCOPE)
  set(GIT_CHANGESET
      "${GIT_COMMIT_HASH}${GIT_MODIFIED}"
      PARENT_SCOPE)
  set(GIT_DESCRIBE
      "${GIT_DESCRIBE}"
      PARENT_SCOPE)
  set(GIT_DESCRIBE_FULL
      "${GIT_DESCRIBE}${GIT_MODIFIED}"
      PARENT_SCOPE)
  set(${ok_var}
      TRUE
      PARENT_SCOPE)
endfunction()

macro(nrn_write_git_info_stamp stamp_file)
  file(
    WRITE "${stamp_file}"
    "# Generated by cmake/NrnGitInfo.cmake. Do not commit.
set(GIT_DATE \"${GIT_DATE}\")
set(GIT_BRANCH \"${GIT_BRANCH}\")
set(GIT_CHANGESET \"${GIT_CHANGESET}\")
set(GIT_DESCRIBE \"${GIT_DESCRIBE}\")
set(GIT_DESCRIBE_FULL \"${GIT_DESCRIBE_FULL}\")
")
endmacro()

if(CMAKE_SCRIPT_MODE_FILE)
  get_filename_component(_nrn_src "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
  nrn_collect_git_info("${_nrn_src}" _nrn_git_ok)
  if(NOT _nrn_git_ok)
    message(FATAL_ERROR "git describe failed in ${_nrn_src}")
  endif()
  set(_nrn_stamp "${CMAKE_CURRENT_LIST_DIR}/nrn-git-info.cmake")
  nrn_write_git_info_stamp("${_nrn_stamp}")
  message(STATUS "Wrote ${_nrn_stamp} ${GIT_CHANGESET} ${GIT_DESCRIBE_FULL}")
endif()
