# =============================================================================
# ~~~
# Execute nrniv to generate an output file and then compare the output file to
# a reference file
#
# Arguments:
#   - executable: nrniv executable
#   - exec_arg: executable arguments
#   - work_dir: working directory
#   - out_file: output file generated by the execution of the executable
#   - ref_file: reference file to compare the out_file
# ~~~
# =============================================================================
execute_process(
  COMMAND ${CMAKE_COMMAND} -E env HOC_LIBRARY_PATH=${hoc_library_path} ${executable} ${exec_arg}
  WORKING_DIRECTORY ${work_dir}
  RESULT_VARIABLE status)
if(status)
  message(FATAL_ERROR "Running exec status: ${status}")
endif()
# --ignore-eol: Windows nrniv writes CRLF; Unix refs are LF. Content match is the rule; byte
# identity is not. CMake 3.14+ (project requires 3.15).
execute_process(
  COMMAND ${CMAKE_COMMAND} -E compare_files --ignore-eol ${out_file} ${ref_file}
  WORKING_DIRECTORY ${work_dir}
  RESULT_VARIABLE status)
if(status)
  # sdiff is a GNU diagnostic, not part of the verdict. Missing on Windows.
  execute_process(
    COMMAND sdiff -s ${out_file} ${ref_file}
    WORKING_DIRECTORY ${work_dir}
    ERROR_QUIET)
  message(FATAL_ERROR "${out_file} differs from ${ref_file} (compare status ${status})")
else()
  file(REMOVE "${work_dir}/${out_file}")
endif()
