name: External build CI

concurrency:
  # Don't cancel on master, creating a PR when a push workflow is already going will cancel the push workflow in favour of the PR workflow
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_id || github.event.number && github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types: [ labeled ]
env:
  PR_URL: ${{ github.event.pull_request.html_url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-last-azure-url:
    name: 'Get Azure URL'
    uses: ./.github/workflows/get-azure-url-template.yml
    if: ${{ github.event.label.name == 'nrn-build-ci-nightly' }}
    with:
      label: ${{ github.event.label.name }}
      ci_name: 'NEURON build CI'
      pr_url: ${{ env.PR_URL }}

  nrn-build-ci:
    name: 'Run build CI'
    needs: get-last-azure-url
    uses: neuronsimulator/nrn-build-ci/.github/workflows/build-neuron-template.yml@master
    with:
      azure_drop_url: ${{needs.get-last-azure-url.outputs.azure_drop_url}}
      neuron_branch: ${{github.head_ref}}
