name: Build custom Docker image for manylinux wheels

on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'The base Docker image to use'
        default: 'manylinux2014'
        type: choice
        options:
          - 'manylinux2014'
          - 'manylinux_2_28'
          - 'manylinux_2_34'

      upload:
        description: 'Whether to upload (push) the image to DockerHub'
        default: 'false'
        required: true
        type: 'boolean'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: 'linux/amd64'
            arch: 'x86_64'
          - platform: 'linux/arm64'
            arch: 'aarch64'

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          push: ${{ github.event.inputs.upload }}
          tags: neuronsimulator/neuron_wheel:latest
          build-args: |
            MANYLINUX_IMAGE: ${{ github.event.inputs.base_image }}_${{ matrix.arch }}
