# Ironically, if this file is not formatted properly, this won't work in the CI
name: Check YAML files

concurrency:
  # Don't cancel on master, creating a PR when a push workflow is already going will cancel the push workflow in favour of the PR workflow
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_id || github.event.number && github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  merge_group:
  push:
    branches:
      - release/**
  pull_request:
    branches:
      - master
      - release/**

jobs:
  all:
    name: Validate YAML files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check all YAML files
        working-directory: ${{runner.workspace}}/nrn
        run: |
          ./ci/validate_yaml.sh
